/* autogenerated by Processing revision 1313 on 2026-06-18 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import processing.serial.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class Benutzeroberflaeche extends PApplet {



/**
 * @file RadarVisualisierung.pde
 * @brief Ausfallsicheres Radar-UI mit Live-Watchdog gegen Kabelbruch und Trennung im Betrieb.
 */

Serial myPort;
String systemState = "BOOT";        
String errorMessage = "";           
String portName = "/dev/cu.usbserial-A106PYCP"; 

float angle = 90;
float distance = 0;

int radarRadius;                    
int maxDistanceCm = 40;
float[] radarWerte = new float[181]; 

int lastConnectionCheck = 0;        
int lastReconnectAttempt = 0;       
int lastDataReceivedTime = 0;       ///< Zeitstempel des letzten gültigen Datenpakets (Watchdog)

public void setup() {
  /* size commented out by preprocessor */;
  /* smooth commented out by preprocessor */;
  
  radarRadius = PApplet.parseInt(height * 0.65f);
  for (int i = 0; i <= 180; i++) { radarWerte[i] = 0; }
  
  connectSerial();
}

public void connectSerial() {
  try {
    myPort = new Serial(this, portName, 9600);
    myPort.bufferUntil('\n');
    systemState = "BOOT"; 
    lastDataReceivedTime = millis(); // Watchdog beim Verbinden zurücksetzen
  } catch (Exception e) {
    systemState = "ERR_PORT";
    errorMessage = "Sicherstellen, dass der Computer mit dem Radarsystem verbunden ist!";
  }
}

public void draw() {
  // ==========================================
  // LIVE-WATCHDOG: Wenn im Zustand OK länger als 500ms keine Daten kommen -> Verbindungsverlust!
  // ==========================================
  if (systemState.equals("OK") && (millis() - lastDataReceivedTime > 500)) {
    systemState = "ERR_PORT";
    try {
      myPort.stop(); // Alten, toten Port sauber schließen
    } catch (Exception e) {}
  }

  // ==========================================
  // SCREEN 1 & 2: PORT-FEHLER ODER HARDWARE-FEHLER (ROTER SCREEN)
  // ==========================================
  if (systemState.equals("ERR_PORT") || systemState.equals("ERR_SENSOR")) {
    background(130, 0, 0); 
    textAlign(CENTER, CENTER);
    
    fill(255);
    textSize(height * 0.07f); 
    text("SYSTEMFEHLER", width/2, height * 0.35f);
    
    textSize(height * 0.035f);
    if (systemState.equals("ERR_PORT")) {
      text("Sicherstellen, dass der Computer mit dem Radarsystem verbunden ist!", width/2, height * 0.52f);
      
      // Versuche alle 2 Sekunden im Hintergrund neu zu verbinden
      if (millis() - lastReconnectAttempt > 2000) {
        connectSerial();
        lastReconnectAttempt = millis();
      }
    } else {
      text("Ultraschallsensor liefert keine Echosignale!", width/2, height * 0.52f);
    }
    
    fill(255, 255, 0); 
    textSize(height * 0.032f);
    text("Anlage überprüfen und Arduino neustarten.", width/2, height * 0.65f);
    return; 
  }

  // ==========================================
  // SCREEN 3: VERBINDUNGSAUFBAU & HARDWARE-HOCHFAHREN (GRAUER SCREEN)
  // ==========================================
  if (systemState.equals("BOOT") || systemState.equals("TESTING")) {
    background(30, 30, 30); 
    textAlign(CENTER, CENTER);
    
    fill(255, 200, 0); 
    textSize(height * 0.06f);
    text("System fährt hoch...", width/2, height * 0.45f);
    
    fill(255, 180, 0, 180);
    textSize(height * 0.035f);
    text("Hardware-Selbsttest wird durchgeführt.", width/2, height * 0.55f);
    
    if (systemState.equals("BOOT") && millis() - lastConnectionCheck > 200) {
      try {
        myPort.write("P:START\n");
      } catch (Exception e) {
        systemState = "ERR_PORT";
      }
      lastConnectionCheck = millis();
    }
    return; 
  }

  // ==========================================
  // SCREEN 4: DER NORMALE LIVE-RADAR-MODUS (GRÜNER SCREEN)
  // ==========================================
  background(6, 12, 6); 
  textAlign(LEFT, BASELINE); 
  
  pushMatrix();
  translate(width/2, height - 80);
  
  // Grid-Kreise zeichnen & beschriften
  strokeWeight(1);
  for (int r = PApplet.parseInt(radarRadius*0.25f); r <= radarRadius; r += PApplet.parseInt(radarRadius*0.25f)) {
    stroke(0, 100, 0, 150);
    noFill();
    arc(0, 0, r*2, r*2, radians(30 - 180), radians(150 - 180)); 
    
    fill(0, 180, 0);
    textSize(13);
    int cmText = PApplet.parseInt(map(r, 0, radarRadius, 0, maxDistanceCm));
    text(cmText + " cm", 10, -r + 5);
  }
  
  // Winkel-Linien & Grad-Beschriftungen
  int[] winkelCheck = {30, 60, 90, 120, 150}; 
  for (int w : winkelCheck) {
    stroke(0, 80, 0, 100);
    float rad = radians(w - 180);
    float lx = radarRadius * cos(rad);
    float ly = radarRadius * sin(rad);
    line(0, 0, lx, ly);
    
    float tx = (radarRadius + 30) * cos(rad);
    float ty = (radarRadius + 30) * sin(rad);
    fill(0, 230, 0);
    textAlign(CENTER, CENTER);
    text(w + "°", tx, ty);
  }
  textAlign(LEFT, BASELINE); 
  
  // Kantenerkennung und Cluster-Darstellung
  boolean inObject = false;
  int startAngle = 0;
  float sumDistance = 0;
  int countPins = 0;
  float lastValidDistance = 0;
  
  for (int i = 30; i <= 150; i++) {
    float d = radarWerte[i];
    if (d > 2 && d <= maxDistanceCm) {
      if (!inObject) {
        inObject = true;
        startAngle = i;
        sumDistance = d;
        countPins = 1;
        lastValidDistance = d;
      } else {
        if (abs(d - lastValidDistance) > 3.5f) {
          drawCompensatedObject(startAngle, i - 1, sumDistance / countPins);
          startAngle = i;
          sumDistance = d;
          countPins = 1;
        } else {
          sumDistance += d;
          countPins++;
        }
        lastValidDistance = d;
      }
    } else {
      if (inObject) {
        drawCompensatedObject(startAngle, i - 1, sumDistance / countPins);
        inObject = false;
      }
    }
  }
  if (inObject) { drawCompensatedObject(startAngle, 150, sumDistance / countPins); }
  
  // Aktueller Abtaststrahl
  strokeWeight(4);
  stroke(0, 255, 0, 220); 
  float pointerX = radarRadius * cos(radians(angle - 180));
  float pointerY = radarRadius * sin(radians(angle - 180));
  line(0, 0, pointerX, pointerY);
  
  popMatrix();
  
  // Dashboard im Vordergrund
  fill(10, 30, 10, 220);
  stroke(0, 255, 0, 80);
  rect(30, 30, 280, 110, 8);
  
  fill(0, 255, 0);
  textSize(16);
  text("RADAR-SYSTEM AKTIV", 45, 60);
  textSize(15);
  text("Winkel: " + PApplet.parseInt(angle) + "°", 45, 90);
  text("Entfernung: " + PApplet.parseInt(distance) + " cm", 45, 115);
}

public void drawCompensatedObject(int startA, int endA, float avgDist) {
  int objectWidthDegrees = endA - startA;
  if (objectWidthDegrees < 2) return;
  
  float centerAngle = startA + (objectWidthDegrees / 2.0f);
  float r = map(avgDist, 0, maxDistanceCm, 0, radarRadius);
  
  stroke(255, 30, 30, 220);
  fill(255, 0, 0, 200);
  
  if (objectWidthDegrees <= 7) {
    float x = r * cos(radians(centerAngle - 180));
    float y = r * sin(radians(centerAngle - 180));
    ellipse(x, y, 8, 8);
  } else {
    strokeWeight(5);
    noFill();
    arc(0, 0, r*2, r*2, radians(startA - 180), radians(endA - 180));
    strokeWeight(1); 
  }
}

public void serialEvent(Serial p) {
  try {
    String inString = p.readStringUntil('\n');
    if (inString != null) {
      inString = trim(inString);
      
      // JEDES Mal, wenn IRGENDWELCHE Daten kommen, setzen wir den Watchdog zurück!
      lastDataReceivedTime = millis(); 
      
      if (inString.startsWith("S:")) {
        String state = inString.substring(2);
        if (state.equals("TESTING")) systemState = "TESTING";
        else if (state.equals("OK")) systemState = "OK";
        else if (state.equals("ERR_SENSOR")) systemState = "ERR_SENSOR";
      } 
      else if (inString.startsWith("D:") && systemState.equals("OK")) {
        String[] data = split(inString.substring(2), ',');
        if (data.length == 2) {
          angle = PApplet.parseFloat(data[0]);
          distance = PApplet.parseFloat(data[1]);
          int index = PApplet.parseInt(angle);
          if (index >= 0 && index <= 180) {
            radarWerte[index] = distance;
          }
        }
      }
    }
  } catch (Exception e) {
    systemState = "ERR_PORT";
  }
}


  public void settings() { fullScreen();
smooth(); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "--full-screen", "--bgcolor=#666666", "--stop-color=#cccccc", "Benutzeroberflaeche" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
